version: 2.1

orbs:
  node: circleci/node@3.0.0

common: &common
  docker:
    - image: circleci/node:10

jobs:
  validate:
    <<: *common

    steps:
      - run:
          command: yarn lint
          when: always

      - run:
          command: yarn test --maxWorkers=2 --colors
          when: always

  build:
    <<: *common

    steps:
      - run: yarn build

workflows:
  version: 2

  delivery:
    jobs:
      - validate
