version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  validate:
    docker:
      - image: circleci/node:10

    steps:
      - run:
          command: yarn lint
          when: always

      - run:
          command: yarn test --maxWorkers=2 --colors
          when: always

  build:
    steps:
      - run: yarn build

workflows:
  node-tests:
    jobs:
      - validate
